import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';

import Container from '@mui/material/Container'
import Paper from '@mui/material/Paper';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';
import { Alert } from '@mui/material';

import NavBar from '../components/NavBar'
import Title from '../components/Title'
import FavouriteBooks from '../components/FavouriteBooks'

const FAVORITEBOOKS = [
  {
    "title": "Harry Potter and the Philosopher's Stone",
    "author": "J.K. Rowling",
    "rating": 9
  },
  {
    "title": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "rating": 8
  }
]


export default function Home() {
  const [books, setBooks] = useState(FAVORITEBOOKS)
  const [title, setTitle] = useState("")
  const [author, setAuthor] = useState("")
  const [rating, setRating] = useState()
  const [hideMessage, sethideMessage] = useState(true)


  const toggleMessage = (event) => {
    if (title == "" || author == "" || rating == 0) {
      sethideMessage(!hideMessage)
    }
    else {
      let newbook =
      {
        "title": title,
        "author": author,
        "rating": rating
      }

      console.log(newbook)
      let newbooklist = [newbook, ...books]
      setBooks(newbooklist)
      sethideMessage(hideMessage)
      setTitle = ""
      setAuthor = ""
      setRating = 0;
    }
  }

  return (
    <div>
      <Head>
        <title>Library App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar title={"Our Library"} />
      <main>
        <Container sx={{ paddingTop: '2rem' }} maxWidth="md">
          <Paper sx={{ p: 2, display: 'flex', flexDirection: 'column', marginBottom: "2rem" }}>
            <Title>Add a New Favourite</Title>
            <form onSubmit={toggleMessage}
            >
              <Grid container spacing={3}>
                <Grid item xs={10} sm={4}>
                  <TextField
                    required
                    id="title"
                    name="title"
                    label="Book Title"
                    fullWidth
                    variant="standard"
                    onChange={(event) => setTitle(event.target.value)}
                    value={title}
                  />
                </Grid>
                <Grid item xs={8} sm={4}>
                  <TextField
                    required
                    id="author"
                    name="author"
                    label="Author"
                    fullWidth
                    variant="standard"
                    onChange={(event) => setAuthor(event.target.value)}
                    value={author}
                  />
                </Grid>
                <Grid item xs={8} sm={2}>
                  <TextField
                    required
                    id="rating"
                    name="rating"
                    label="Rating"
                    fullWidth
                    variant="standard"
                    onChange={(event) => setRating(parseInt(event.target.value))}
                    //value={`${rating}`}
                    value={rating}
                  />
                </Grid>
                <Grid item xs={2} sm={2}>
                  <Button variant="contained" onClick={toggleMessage} sx={{ mt: 1.5, ml: 1 }}>

                    Add</Button>
                </Grid>
              </Grid>
            </form>
            {!hideMessage && <Alert severity="error">All values must be entered</Alert>}
          </Paper>
          <FavouriteBooks books={books} />
        </Container>
      </main>
    </div>
  )
}
